version: '2'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    depends_on:
      - zookeeper
  mongo:
    image: 'mongo:4.0.0'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo_data:/data/db'
  gallery:
    image: 'gallery:latest'
    ports:
      - '8080:8080'
    volumes:
      - 'gallery_data:/data'
    environment:
      - GALLERY_DATABASE_URL=mongodb://mongo:27017
      - GALLERY_KAFKA_URL=kafka:9092
    depends_on:
      - mongo
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongo_data:
    driver: local
  gallery_data:
    driver: local